[
  { "id": "ai-1", "module": "/ai", "commande": "swarm_deploy", "description": "Essaim d'agents IA déployé pour projet", "categorie": "Intelligence" },
  { "id": "ai-2", "module": "/ai", "commande": "auto_refactor", "description": "Refactorisation automatique du code", "categorie": "Intelligence" },
  { "id": "ai-3", "module": "/ai", "commande": "deep_scan", "description": "Module IA analysé en profondeur", "categorie": "Intelligence" },
  { "id": "ai-4", "module": "/ai", "commande": "predictive_patch", "description": "Correctifs prédictifs générés", "categorie": "Intelligence" },
  { "id": "ai-5", "module": "/ai", "commande": "hyper_optimize", "description": "Workflow IA optimisé en parallèle", "categorie": "Intelligence" },

  { "id": "sec-1", "module": "/sec", "commande": "ghost_scan", "description": "Scan réseau ultra-discret", "categorie": "Sécurité" },
  { "id": "sec-2", "module": "/sec", "commande": "quantum_encrypt", "description": "Chiffrement post-quantum", "categorie": "Sécurité" },
  { "id": "sec-3", "module": "/sec", "commande": "intrusion_simulate", "description": "Simulation d'attaque réseau", "categorie": "Sécurité" },
  { "id": "sec-4", "module": "/sec", "commande": "auto_patch", "description": "Patchs appliqués automatiquement", "categorie": "Sécurité" },
  { "id": "sec-5", "module": "/sec", "commande": "shield_matrix", "description": "Bouclier dynamique activé", "categorie": "Sécurité" },

  { "id": "dev-1", "module": "/dev", "commande": "nano_generate", "description": "Module minimaliste généré", "categorie": "Développement" },
  { "id": "dev-2", "module": "/dev", "commande": "tsx_dynamic", "description": "Composant TSX adaptatif créé", "categorie": "Développement" },
  { "id": "dev-3", "module": "/dev", "commande": "flutter_hybrid", "description": "App Flutter multi-plateformes générée", "categorie": "Développement" },
  { "id": "dev-4", "module": "/dev", "commande": "auto_api", "description": "API complète générée automatiquement", "categorie": "Développement" },
  { "id": "dev-5", "module": "/dev", "commande": "multi_agent", "description": "Projet déployé avec agents IA multiples", "categorie": "Développement" },

  { "id": "net-1", "module": "/net", "commande": "stealth_proxy", "description": "Tunnel ultra-discret activé", "categorie": "Réseau" },
  { "id": "net-2", "module": "/net", "commande": "neural_monitor", "description": "Surveillance réseau intelligente", "categorie": "Réseau" },
  { "id": "net-3", "module": "/net", "commande": "auto_crawl", "description": "Collecte de données automatique", "categorie": "Réseau" },
  { "id": "net-4", "module": "/net", "commande": "flux_merge", "description": "Fusion flux multiples", "categorie": "Réseau" },
  { "id": "net-5", "module": "/net", "commande": "quantum_sync", "description": "Synchronisation quantique", "categorie": "Réseau" },

  { "id": "gen-1", "module": "/gen", "commande": "auto_startup", "description": "Architecture startup générée", "categorie": "Génération" },
  { "id": "gen-2", "module": "/gen", "commande": "ai_model_full", "description": "Modèle IA complet prêt production", "categorie": "Génération" },
  { "id": "gen-3", "module": "/gen", "commande": "full_stack", "description": "Projet full-stack généré", "categorie": "Génération" },
  { "id": "gen-4", "module": "/gen", "commande": "deploy_cloud", "description": "Déploiement cloud automatique", "categorie": "Génération" },
  { "id": "gen-5", "module": "/gen", "commande": "swarm_ai", "description": "Essaim IA déployé", "categorie": "Génération" },

  { "id": "kernel-1", "module": "/kernel", "commande": "inject_memory", "description": "Mémoire virtuelle injectée pour agents IA", "categorie": "Noyau" },
  { "id": "kernel-2", "module": "/kernel", "commande": "override_process", "description": "Contrôle processus système", "categorie": "Noyau" },

  { "id": "cmd-1", "module": "/cmd", "commande": "cmd_1", "description": "Exécution commande experte #1", "categorie": "Expert" },
  { "id": "cmd-2", "module": "/cmd", "commande": "cmd_2", "description": "Exécution commande experte #2", "categorie": "Expert" },
  { "id": "cmd-3", "module": "/cmd", "commande": "cmd_3", "description": "Exécution commande experte #3", "categorie": "Expert" },
  { "id": "cmd-4", "module": "/cmd", "commande": "cmd_4", "description": "Exécution commande experte #4", "categorie": "Expert" },
  { "id": "cmd-5", "module": "/cmd", "commande": "cmd_5", "description": "Exécution commande experte #5", "categorie": "Expert" },
  { "id": "cmd-6", "module": "/cmd", "commande": "cmd_6", "description": "Exécution commande experte #6", "categorie": "Expert" },
  { "id": "cmd-7", "module": "/cmd", "commande": "cmd_7", "description": "Exécution commande experte #7", "categorie": "Expert" },
  { "id": "cmd-8", "module": "/cmd", "commande": "cmd_8", "description": "Exécution commande experte #8", "categorie": "Expert" },
  { "id": "cmd-9", "module": "/cmd", "commande": "cmd_9", "description": "Exécution commande experte #9", "categorie": "Expert" },
  { "id": "cmd-10", "module": "/cmd", "commande": "cmd_10", "description": "Exécution commande experte #10", "categorie": "Expert" },
  { "id": "cmd-11", "module": "/cmd", "commande": "cmd_11", "description": "Exécution commande experte #11", "categorie": "Expert" },
  { "id": "cmd-12", "module": "/cmd", "commande": "cmd_12", "description": "Exécution commande experte #12", "categorie": "Expert" },
  { "id": "cmd-13", "module": "/cmd", "commande": "cmd_13", "description": "Exécution commande experte #13", "categorie": "Expert" },
  { "id": "cmd-14", "module": "/cmd", "commande": "cmd_14", "description": "Exécution commande experte #14", "categorie": "Expert" },
  { "id": "cmd-15", "module": "/cmd", "commande": "cmd_15", "description": "Exécution commande experte #15", "categorie": "Expert" },
  { "id": "cmd-16", "module": "/cmd", "commande": "cmd_16", "description": "Exécution commande experte #16", "categorie": "Expert" },
  { "id": "cmd-17", "module": "/cmd", "commande": "cmd_17", "description": "Exécution commande experte #17", "categorie": "Expert" },
  { "id": "cmd-18", "module": "/cmd", "commande": "cmd_18", "description": "Exécution commande experte #18", "categorie": "Expert" },
  { "id": "cmd-19", "module": "/cmd", "commande": "cmd_19", "description": "Exécution commande experte #19", "categorie": "Expert" },
  { "id": "cmd-20", "module": "/cmd", "commande": "cmd_20", "description": "Exécution commande experte #20", "categorie": "Expert" },
  { "id": "cmd-21", "module": "/cmd", "commande": "cmd_21", "description": "Exécution commande experte #21", "categorie": "Expert" },
  { "id": "cmd-22", "module": "/cmd", "commande": "cmd_22", "description": "Exécution commande experte #22", "categorie": "Expert" },
  { "id": "cmd-23", "module": "/cmd", "commande": "cmd_23", "description": "Exécution commande experte #23", "categorie": "Expert" },
  { "id": "cmd-24", "module": "/cmd", "commande": "cmd_24", "description": "Exécution commande experte #24", "categorie": "Expert" },
  { "id": "cmd-25", "module": "/cmd", "commande": "cmd_25", "description": "Exécution commande experte #25", "categorie": "Expert" },
  { "id": "cmd-26", "module": "/cmd", "commande": "cmd_26", "description": "Exécution commande experte #26", "categorie": "Expert" },
  { "id": "cmd-27", "module": "/cmd", "commande": "cmd_27", "description": "Exécution commande experte #27", "categorie": "Expert" },
  { "id": "cmd-28", "module": "/cmd", "commande": "cmd_28", "description": "Exécution commande experte #28", "categorie": "Expert" },
  { "id": "cmd-29", "module": "/cmd", "commande": "cmd_29", "description": "Exécution commande experte #29", "categorie": "Expert" },
  { "id": "cmd-30", "module": "/cmd", "commande": "cmd_30", "description": "Exécution commande experte #30", "categorie": "Expert" },
  { "id": "cmd-31", "module": "/cmd", "commande": "cmd_31", "description": "Exécution commande experte #31", "categorie": "Expert" },
  { "id": "cmd-32", "module": "/cmd", "commande": "cmd_32", "description": "Exécution commande experte #32", "categorie": "Expert" },
  { "id": "cmd-33", "module": "/cmd", "commande": "cmd_33", "description": "Exécution commande experte #33", "categorie": "Expert" },
  { "id": "cmd-34", "module": "/cmd", "commande": "cmd_34", "description": "Exécution commande experte #34", "categorie": "Expert" },
  { "id": "cmd-35", "module": "/cmd", "commande": "cmd_35", "description": "Exécution commande experte #35", "categorie": "Expert" },
  { "id": "cmd-36", "module": "/cmd", "commande": "cmd_36", "description": "Exécution commande experte #36", "categorie": "Expert" },
  { "id": "cmd-37", "module": "/cmd", "commande": "cmd_37", "description": "Exécution commande experte #37", "categorie": "Expert" },
  { "id": "cmd-38", "module": "/cmd", "commande": "cmd_38", "description": "Exécution commande experte #38", "categorie": "Expert" },
  { "id": "cmd-39", "module": "/cmd", "commande": "cmd_39", "description": "Exécution commande experte #39", "categorie": "Expert" },
  { "id": "cmd-40", "module": "/cmd", "commande": "cmd_40", "description": "Exécution commande experte #40", "categorie": "Expert" },
  { "id": "cmd-41", "module": "/cmd", "commande": "cmd_41", "description": "Exécution commande experte #41", "categorie": "Expert" },
  { "id": "cmd-42", "module": "/cmd", "commande": "cmd_42", "description": "Exécution commande experte #42", "categorie": "Expert" },
  { "id": "cmd-43", "module": "/cmd", "commande": "cmd_43", "description": "Exécution commande experte #43", "categorie": "Expert" },
  { "id": "cmd-44", "module": "/cmd", "commande": "cmd_44", "description": "Exécution commande experte #44", "categorie": "Expert" },
  { "id": "cmd-45", "module": "/cmd", "commande": "cmd_45", "description": "Exécution commande experte #45", "categorie": "Expert" },
  { "id": "cmd-46", "module": "/cmd", "commande": "cmd_46", "description": "Exécution commande experte #46", "categorie": "Expert" },
  { "id": "cmd-47", "module": "/cmd", "commande": "cmd_47", "description": "Exécution commande experte #47", "categorie": "Expert" },
  { "id": "cmd-48", "module": "/cmd", "commande": "cmd_48", "description": "Exécution commande experte #48", "categorie": "Expert" },
  { "id": "cmd-49", "module": "/cmd", "commande": "cmd_49", "description": "Exécution commande experte #49", "categorie": "Expert" },
  { "id": "cmd-50", "module": "/cmd", "commande": "cmd_50", "description": "Exécution commande experte #50", "categorie": "Expert" },
  { "id": "cmd-51", "module": "/cmd", "commande": "cmd_51", "description": "Exécution commande experte #51", "categorie": "Expert" },
  { "id": "cmd-52", "module": "/cmd", "commande": "cmd_52", "description": "Exécution commande experte #52", "categorie": "Expert" },
  { "id": "cmd-53", "module": "/cmd", "commande": "cmd_53", "description": "Exécution commande experte #53", "categorie": "Expert" },
  { "id": "cmd-54", "module": "/cmd", "commande": "cmd_54", "description": "Exécution commande experte #54", "categorie": "Expert" },
  { "id": "cmd-55", "module": "/cmd", "commande": "cmd_55", "description": "Exécution commande experte #55", "categorie": "Expert" },
  { "id": "cmd-56", "module": "/cmd", "commande": "cmd_56", "description": "Exécution commande experte #56", "categorie": "Expert" },
  { "id": "cmd-57", "module": "/cmd", "commande": "cmd_57", "description": "Exécution commande experte #57", "categorie": "Expert" },
  { "id": "cmd-58", "module": "/cmd", "commande": "cmd_58", "description": "Exécution commande experte #58", "categorie": "Expert" },
  { "id": "cmd-59", "module": "/cmd", "commande": "cmd_59", "description": "Exécution commande experte #59", "categorie": "Expert" },
  { "id": "cmd-60", "module": "/cmd", "commande": "cmd_60", "description": "Exécution commande experte #60", "categorie": "Expert" },
  { "id": "cmd-61", "module": "/cmd", "commande": "cmd_61", "description": "Exécution commande experte #61", "categorie": "Expert" },
  { "id": "cmd-62", "module": "/cmd", "commande": "cmd_62", "description": "Exécution commande experte #62", "categorie": "Expert" },
  { "id": "cmd-63", "module": "/cmd", "commande": "cmd_63", "description": "Exécution commande experte #63", "categorie": "Expert" },
  { "id": "cmd-64", "module": "/cmd", "commande": "cmd_64", "description": "Exécution commande experte #64", "categorie": "Expert" },
  { "id": "cmd-65", "module": "/cmd", "commande": "cmd_65", "description": "Exécution commande experte #65", "categorie": "Expert" },
  { "id": "cmd-66", "module": "/cmd", "commande": "cmd_66", "description": "Exécution commande experte #66", "categorie": "Expert" },
  { "id": "cmd-67", "module": "/cmd", "commande": "cmd_67", "description": "Exécution commande experte #67", "categorie": "Expert" },
  { "id": "cmd-68", "module": "/cmd", "commande": "cmd_68", "description": "Exécution commande experte #68", "categorie": "Expert" },
  { "id": "cmd-69", "module": "/cmd", "commande": "cmd_69", "description": "Exécution commande experte #69", "categorie": "Expert" },
  { "id": "cmd-70", "module": "/cmd", "commande": "cmd_70", "description": "Exécution commande experte #70", "categorie": "Expert" },
  { "id": "cmd-71", "module": "/cmd", "commande": "cmd_71", "description": "Exécution commande experte #71", "categorie": "Expert" },
  { "id": "cmd-72", "module": "/cmd", "commande": "cmd_72", "description": "Exécution commande experte #72", "categorie": "Expert" },
  { "id": "cmd-73", "module": "/cmd", "commande": "cmd_73", "description": "Exécution commande experte #73", "categorie": "Expert" },
  { "id": "cmd-74", "module": "/cmd", "commande": "cmd_74", "description": "Exécution commande experte #74", "categorie": "Expert" },
  { "id": "cmd-75", "module": "/cmd", "commande": "cmd_75", "description": "Exécution commande experte #75", "categorie": "Expert" },
  { "id": "cmd-76", "module": "/cmd", "commande": "cmd_76", "description": "Exécution commande experte #76", "categorie": "Expert" },
  { "id": "cmd-77", "module": "/cmd", "commande": "cmd_77", "description": "Exécution commande experte #77", "categorie": "Expert" },
  { "id": "cmd-78", "module": "/cmd", "commande": "cmd_78", "description": "Exécution commande experte #78", "categorie": "Expert" },
  { "id": "cmd-79", "module": "/cmd", "commande": "cmd_79", "description": "Exécution commande experte #79", "categorie": "Expert" },
  { "id": "cmd-80", "module": "/cmd", "commande": "cmd_80", "description": "Exécution commande experte #80", "categorie": "Expert" },
  { "id": "cmd-81", "module": "/cmd", "commande": "cmd_81", "description": "Exécution commande experte #81", "categorie": "Expert" },
  { "id": "cmd-82", "module": "/cmd", "commande": "cmd_82", "description": "Exécution commande experte #82", "categorie": "Expert" },
  { "id": "cmd-83", "module": "/cmd", "commande": "cmd_83", "description": "Exécution commande experte #83", "categorie": "Expert" },
  { "id": "cmd-84", "module": "/cmd", "commande": "cmd_84", "description": "Exécution commande experte #84", "categorie": "Expert" },
  { "id": "cmd-85", "module": "/cmd", "commande": "cmd_85", "description": "Exécution commande experte #85", "categorie": "Expert" },
  { "id": "cmd-86", "module": "/cmd", "commande": "cmd_86", "description": "Exécution commande experte #86", "categorie": "Expert" },
  { "id": "cmd-87", "module": "/cmd", "commande": "cmd_87", "description": "Exécution commande experte #87", "categorie": "Expert" },
  { "id": "cmd-88", "module": "/cmd", "commande": "cmd_88", "description": "Exécution commande experte #88", "categorie": "Expert" },
  { "id": "cmd-89", "module": "/cmd", "commande": "cmd_89", "description": "Exécution commande experte #89", "categorie": "Expert" },
  { "id": "cmd-90", "module": "/cmd", "commande": "cmd_90", "description": "Exécution commande experte #90", "categorie": "Expert" },
  { "id": "cmd-91", "module": "/cmd", "commande": "cmd_91", "description": "Exécution commande experte #91", "categorie": "Expert" },
  { "id": "cmd-92", "module": "/cmd", "commande": "cmd_92", "description": "Exécution commande experte #92", "categorie": "Expert" },
  { "id": "cmd-93", "module": "/cmd", "commande": "cmd_93", "description": "Exécution commande experte #93", "categorie": "Expert" },
  { "id": "cmd-94", "module": "/cmd", "commande": "cmd_94", "description": "Exécution commande experte #94", "categorie": "Expert" },
  { "id": "cmd-95", "module": "/cmd", "commande": "cmd_95", "description": "Exécution commande experte #95", "categorie": "Expert" },
  { "id": "cmd-96", "module": "/cmd", "commande": "cmd_96", "description": "Exécution commande experte #96", "categorie": "Expert" },
  { "id": "cmd-97", "module": "/cmd", "commande": "cmd_97", "description": "Exécution commande experte #97", "categorie": "Expert" },
  { "id": "cmd-98", "module": "/cmd", "commande": "cmd_98", "description": "Exécution commande experte #98", "categorie": "Expert" },
  { "id": "cmd-99", "module": "/cmd", "commande": "cmd_99", "description": "Exécution commande experte #99", "categorie": "Expert" },
  { "id": "cmd-100", "module": "/cmd", "commande": "cmd_100", "description": "Exécution commande experte #100", "categorie": "Expert" },
  { "id": "cmd-101", "module": "/cmd", "commande": "cmd_101", "description": "Exécution commande experte #101", "categorie": "Expert" },
  { "id": "cmd-102", "module": "/cmd", "commande": "cmd_102", "description": "Exécution commande experte #102", "categorie": "Expert" },
  { "id": "cmd-103", "module": "/cmd", "commande": "cmd_103", "description": "Exécution commande experte #103", "categorie": "Expert" },
  { "id": "cmd-104", "module": "/cmd", "commande": "cmd_104", "description": "Exécution commande experte #104", "categorie": "Expert" },
  { "id": "cmd-105", "module": "/cmd", "commande": "cmd_105", "description": "Exécution commande experte #105", "categorie": "Expert" },
  { "id": "cmd-106", "module": "/cmd", "commande": "cmd_106", "description": "Exécution commande experte #106", "categorie": "Expert" },
  { "id": "cmd-107", "module": "/cmd", "commande": "cmd_107", "description": "Exécution commande experte #107", "categorie": "Expert" },
  { "id": "cmd-108", "module": "/cmd", "commande": "cmd_108", "description": "Exécution commande experte #108", "categorie": "Expert" },
  { "id": "cmd-109", "module": "/cmd", "commande": "cmd_109", "description": "Exécution commande experte #109", "categorie": "Expert" },
  { "id": "cmd-110", "module": "/cmd", "commande": "cmd_110", "description": "Exécution commande experte #110", "categorie": "Expert" },
  { "id": "cmd-111", "module": "/cmd", "commande": "cmd_111", "description": "Exécution commande experte #111", "categorie": "Expert" },
  { "id": "cmd-112", "module": "/cmd", "commande": "cmd_112", "description": "Exécution commande experte #112", "categorie": "Expert" },
  { "id": "cmd-113", "module": "/cmd", "commande": "cmd_113", "description": "Exécution commande experte #113", "categorie": "Expert" },
  { "id": "cmd-114", "module": "/cmd", "commande": "cmd_114", "description": "Exécution commande experte #114", "categorie": "Expert" },
  { "id": "cmd-115", "module": "/cmd", "commande": "cmd_115", "description": "Exécution commande experte #115", "categorie": "Expert" },
  { "id": "cmd-116", "module": "/cmd", "commande": "cmd_116", "description": "Exécution commande experte #116", "categorie": "Expert" },
  { "id": "cmd-117", "module": "/cmd", "commande": "cmd_117", "description": "Exécution commande experte #117", "categorie": "Expert" },
  { "id": "cmd-118", "module": "/cmd", "commande": "cmd_118", "description": "Exécution commande experte #118", "categorie": "Expert" },
  { "id": "cmd-119", "module": "/cmd", "commande": "cmd_119", "description": "Exécution commande experte #119", "categorie": "Expert" },
  { "id": "cmd-120", "module": "/cmd", "commande": "cmd_120", "description": "Exécution commande experte #120", "categorie": "Expert" }
]
